# .github/workflows/semgrep.yml
name: Full-Stack SAST Scan (Semgrep)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Run Semgrep Scan
      - name: Run Semgrep Scan
        # CORRECTED LINE: Using semgrep/semgrep-action
        uses: semgrep/semgrep-action@v1 
        with:
          config: auto
          github_token: ${{ secrets.GITHUB_TOKEN }}
